name: Linting

on:
  push:
    branches:
      - main
      - master
      - dev
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: pre-commit
    steps:
      - uses: actions/checkout@v2.5.0
      - uses: actions/setup-python@v2.3.3
        with:
          python-version: "3.10"
      - run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip install --constraint=.github/workflows/constraints.txt pre-commit
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit-4|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - uses: actions/cache@v3.0.11
        if: matrix.os != 'windows-latest'
        with:
          path: ~/.cache/pre-commit
          key: ${{ steps.cache_key_prefix.outputs.result }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ steps.cache_key_prefix.outputs.result }}-
      - run: pre-commit run --all-files --show-diff-on-failure --color=always
